CC = gcc
CFLAGS = -Wall -g -lm

# Targets to build
programa1: programa1.c grafo.c
	$(CC) $(CFLAGS) -o programa1 programa1.c grafo.c

programa2: programa2.c grafo.c
	$(CC) $(CFLAGS) -o programa2 programa2.c grafo.c

clean:
	rm -f programa1 programa2
